name: Sum Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - testBranch
  merge_group:
    branches:
      - main

env:
    env_var: ${{vars.env_uat}}

jobs:
  sumTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node Version
        uses: actions/setup-node@v2
        with:
          node-version: 21.x

      - name: Install Packages
        run: npm ci

      - name: Run Tests
        run: npm test

  echoIfPassed:
    needs: sumTest
    runs-on: ubuntu-latest
    # if: github.event_name == 'pull_request' && github.event.action != 'closed'
    steps:
      - name: Echo the Pass results and env
        run: echo "The Test cases have passed and this is the  ${{vars.env_uat}}!!" 
      - name: Echo the Pass results and secrets
        run: echo "The Test cases have passed and this is the secrets!! ${{secrets.SOMEAUTHSECRET}}" 
