name: Sum Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sumTest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node Version
        uses: actions/setup-node@v2
        with:
          node-version: 21.x

      - name: Install Packages
        run: npm ci

      - name: Run Tests
        run: npm test

  echoIfPassed:
    needs: sumTest
    runs-on: ubuntu-latest

    steps:
      - name: Echo the Pass results
        run: echo "The Test cases have passed!!"
